name: IntelliJ Platform Plugin Compatibility

on: [push, pull_request]

jobs:
  compatibility:
    name: Ensure plugin compatibility against supported platforms.
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin
        env:
          IS_CI: "True"

      - name: Verify Plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@v0.0.1
        with:
          ide-versions: |
            ideaIC:2020.1
            pycharmPC:2020.1
            clion:2020.1
            ideaIC:LATEST-EAP-SNAPSHOT
            pycharmPC:LATEST-EAP-SNAPSHOT
            clion:LATEST-EAP-SNAPSHOT

      - name: Get log file path and print contents
        run: |
          echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}
